export const TecnologiesObjs = [
    {
        id:1,
        name:'Frontend',
        img:'https://img.icons8.com/external-kiranshastry-lineal-kiranshastry/64/A7D129/external-coding-interface-kiranshastry-lineal-kiranshastry.png',
        tecnology:[
            {
                img:'https://img.icons8.com/color/48/000000/html-5--v1.svg',
                nameTecnology:'HTML'
            },
            {
                img:'https://img.icons8.com/color/48/000000/css3.svg',
                nameTecnology:'CSS'
            },
            {
                img:'https://img.icons8.com/fluency/48/000000/javascript.svg',
                nameTecnology:'JavaScript'
            },
            {
                img:'https://img.icons8.com/color/48/000000/bootstrap.svg',
                nameTecnology:'Bootstrap'
            },
            {
                img:'https://img.icons8.com/office/48/000000/react.svg',
                nameTecnology:'React'
            },
            {
                img:'https://img.icons8.com/color/48/000000/tailwind_css.svg',
                nameTecnology:'Tailwind'
            },
        ]
    },
    {
        id:2,
        name:'Backend',
        img:'https://img.icons8.com/windows/96/A7D129/placeholder-thumbnail-json-1.png',
        tecnology:[
            {
                img:'https://img.icons8.com/officel/48/000000/php-logo.svg',
                nameTecnology:'PHP'
            },
            {
                img:'https://img.icons8.com/fluency/48/000000/laravel.png',
                nameTecnology:'Laravel'
            },
            {
                img:'https://img.icons8.com/fluency/48/000000/node-js.svg',
                nameTecnology:'Node JS'
            },
            {
                img:'https://img.icons8.com/color/48/000000/python--v1.svg',
                nameTecnology:'Python'
            },
            {
                img:'https://img.icons8.com/ios/48/A7D129/flask.svg',
                nameTecnology:'Flask'
            },
            {
                img:'https://img.icons8.com/color/48/000000/java-coffee-cup-logo--v1.svg',
                nameTecnology:'Java'
            },
        ]
    },
    {
        id:3,
        name:'Bases de datos',
        img:'https://img.icons8.com/ios/50/A7D129/database.png',
        tecnology:[
            {
                img:'https://img.icons8.com/color/48/000000/mysql-logo.svg',
                nameTecnology:'MySQL'
            },
            {
                img:'https://img.icons8.com/material-outlined/48/000000/mysql-logo.svg',
                nameTecnology:'MySQL Workbench'
            },
            {
                img:'https://img.icons8.com/color/48/000000/mongodb.svg',
                nameTecnology:'MongoDB'
            },
            {
                img:'https://img.icons8.com/color/48/000000/cloud-firestore.png',
                nameTecnology:'Firestore'
            },
            {
                img:'https://img.icons8.com/windows/48/000000/project-diagram.png',
                nameTecnology:'DiagramIO'
            },
            
        ]
    },
    {
        id:4,
        name:'Cloud',
        img:'https://img.icons8.com/material-outlined/96/A7D129/cloud--v1.png',
        tecnology:[
            {
                img:'https://img.icons8.com/color/48/000000/azure-1.svg',
                nameTecnology:'Azure'
            },
            {
                img:'https://img.icons8.com/color/48/000000/google-cloud.svg',
                nameTecnology:'Google Cloud'
            },
            {
                img:'https://img.icons8.com/color/48/000000/firebase.png',
                nameTecnology:'Firebase'
            },
        ]
    },
    {
        id:5,
        name:'Otros',
        img:'https://img.icons8.com/ios-glyphs/90/A7D129/plus--v1.svg',
        tecnology:[
            {
                img:'https://img.icons8.com/color/48/000000/git.svg',
                nameTecnology:'Git'
            },
            {
                img:'https://img.icons8.com/color/48/000000/github--v1.svg',
                nameTecnology:'GitHub'
            },
            {
                img:'https://img.icons8.com/external-tal-revivo-shadow-tal-revivo/48/000000/external-postman-is-the-only-complete-api-development-environment-logo-shadow-tal-revivo.png',
                nameTecnology:'Postman'
            },
            {
                img:'https://img.icons8.com/dusk/48/000000/ssh.png',
                nameTecnology:'MobaXterm'
            },
            {
                img:'https://img.icons8.com/color/48/000000/filezilla.svg',
                nameTecnology:'FileZilla'
            },
            {
                img:'https://img.icons8.com/color-glass/48/000000/adobe-illustrator.svg',
                nameTecnology:'Illustrator'
            },
            {
                img:'https://img.icons8.com/color/48/000000/sony-vegas.svg',
                nameTecnology:'Vegas Pro'
            },
            {
                img:'https://img.icons8.com/color/48/000000/figma--v1.png',
                nameTecnology:'Figma'
            },
        ]
    },
];