export const TecnologiesObjs = [
    {
        id:1,
        name:'Frontend',
        img:'https://img.icons8.com/external-kiranshastry-lineal-kiranshastry/64/A7D129/external-coding-interface-kiranshastry-lineal-kiranshastry.png',
        tecnology:[
            {
                img:'https://img.icons8.com/color/48/000000/html-5--v1.png',
                nameTecnology:'HTML'
            },
            {
                img:'https://img.icons8.com/color/48/000000/css3.png',
                nameTecnology:'CSS'
            },
            {
                img:'https://img.icons8.com/fluency/48/000000/javascript.png',
                nameTecnology:'JavaScript'
            },
            {
                img:'https://img.icons8.com/color/48/000000/bootstrap.png',
                nameTecnology:'Bootstrap'
            },
            {
                img:'https://img.icons8.com/office/48/000000/react.png',
                nameTecnology:'React'
            },
            {
                img:'https://img.icons8.com/color/48/000000/tailwind_css.png',
                nameTecnology:'Tailwind'
            },
        ]
    },
    {
        id:2,
        name:'Backend',
        img:'https://img.icons8.com/windows/96/A7D129/placeholder-thumbnail-json-1.png',
        tecnology:[
            {
                img:'test1',
                nameTecnology:'test1'
            },
            {
                img:'test2',
                nameTecnology:'test2'
            },
            {
                img:'test3',
                nameTecnology:'test3'
            },
            {
                img:'test4',
                nameTecnology:'test4'
            },
            {
                img:'test5',
                nameTecnology:'test5'
            },
        ]
    },
    {
        id:3,
        name:'Bases de datos',
        img:'https://img.icons8.com/ios/50/A7D129/database.png',
        tecnology:[
            {
                img:'test1',
                nameTecnology:'test1'
            },
            {
                img:'test2',
                nameTecnology:'test2'
            },
            {
                img:'test3',
                nameTecnology:'test3'
            },
            {
                img:'test4',
                nameTecnology:'test4'
            },
            {
                img:'test5',
                nameTecnology:'test5'
            },
        ]
    },
    {
        id:4,
        name:'Cloud',
        img:'https://img.icons8.com/material-outlined/96/A7D129/cloud--v1.png',
        tecnology:[
            {
                img:'test1',
                nameTecnology:'test1'
            },
            {
                img:'test2',
                nameTecnology:'test2'
            },
            {
                img:'test3',
                nameTecnology:'test3'
            },
            {
                img:'test4',
                nameTecnology:'test4'
            },
            {
                img:'test5',
                nameTecnology:'test5'
            },
        ]
    },
    {
        id:5,
        name:'Otros',
        img:'https://img.icons8.com/ios-glyphs/90/A7D129/plus--v1.png',
        tecnology:[
            {
                img:'test1',
                nameTecnology:'test1'
            },
            {
                img:'test2',
                nameTecnology:'test2'
            },
            {
                img:'test3',
                nameTecnology:'test3'
            },
            {
                img:'test4',
                nameTecnology:'test4'
            },
            {
                img:'test5',
                nameTecnology:'test5'
            },
        ]
    },
];